ALTER TABLE model ADD COLUMN burn_in_iterations INT NOT NULL DEFAULT 5000;
ALTER TABLE model ADD COLUMN inference_iterations INT NOT NULL DEFAULT 20000;
ALTER TABLE model ADD COLUMN thinning_factor INT NOT NULL DEFAULT 10;
